[package]
name = "sketches"
version = "0.1.0"
authors = ["mmansion <mikhail@transmission.studio>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.12"

[dev-dependencies]
audrey = "0.2"
nannou_audio = "0.2"
nannou_laser = "0.3"
nannou_osc = "0.1"
shade_runner = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
moltenvk_deps = "0.1"

# --------------- Nannou Sketches
[[examples]]
name = "osc_receiver"
path = "examples/osc_receiver.rs"
[[examples]]
name = "basic_shapes"
path = "examples/basic_shapes.rs"
[[examples]]
name = "basic_forces"
path = "examples/basic_forces.rs"
[[examples]]
name = "aquatic_juice"
path = "examples/aquatic_juice.rs"
[[examples]]
name = "delicate_umbrella"
path = "examples/delicate_umbrella.rs"
[[examples]]
name = "polyline"
path = "examples/polyline.rs"