[workspace]

members = [
    "library",
    "library-dev",
    # "templates",
    # "n-series",
    # "examples",
    # "nannou_touchosc",
    # "sketches",
    #"tutorials/schotter1",
]

resolver = "2"