[workspace]

members = [
    "library",
    "library-dev",
    # "templates",
    "examples",
    "nannou_touchosc",
    "sketches",
    #"tutorials/schotter1",
    'rust_patterns/*',
    'nature-pix'
]

resolver = "2"